pipeline {
agent any

```
environment {
    AWS_REGION = "ap-south-1"
}

stages {

    stage('Checkout Source') {
        steps {
            checkout scm
        }
    }

    stage('Verify Terraform') {
        steps {
            sh 'terraform version'
        }
    }

    stage('Terraform Init') {
        steps {
            dir('terraform') {
                sh 'terraform init'
            }
        }
    }

    stage('Terraform Format Check') {
        steps {
            dir('terraform') {
                sh 'terraform fmt -check'
            }
        }
    }

    stage('Terraform Validate') {
        steps {
            dir('terraform') {
                sh 'terraform validate'
            }
        }
    }

    stage('Terraform Plan') {
        steps {
            dir('terraform') {
                sh 'terraform plan -out=tfplan'
            }
        }
    }

    stage('Terraform Apply') {
        steps {
            dir('terraform') {
                sh 'terraform apply -auto-approve tfplan'
            }
        }
    }

    stage('Verify EKS') {
        steps {
            sh '''
            aws eks update-kubeconfig \
            --region ap-south-1 \
            --name devops-eks
            '''

            sh 'kubectl get nodes'
        }
    }
}

post {

    success {
        echo 'Terraform Infrastructure Created Successfully'
    }

    failure {
        echo 'Terraform Deployment Failed'
    }
}
```

}


